<?php
use klr\Environment;

echo " <div class='row'> ";
echo "     <div class='col-xl-3 col-sm-6 mb-xl-0 mb-4'>  ";
echo "         <div class='card'> ";
echo "         <div class='card-header p-3 pt-2'> ";
echo "             <div class='icon icon-lg icon-shape bg-gradient-dark shadow-dark text-center border-radius-xl mt-n4 position-absolute'> ";
echo "             <i class='bi bi-cash-coin h2'></i> ";
echo "             </div> ";
echo "             <div class='text-end pt-1'> ";
echo "             <p class='text-sm mb-0 text-capitalize'>Today's Money</p> ";
echo "             <h4 class='mb-0'>$53k</h4> ";
echo "             </div> ";
echo "         </div> ";
echo "         <hr class='dark horizontal my-0'> ";
echo "         <div class='card-footer p-3'> ";
echo "             <p class='mb-0'><span class='text-success text-sm font-weight-bolder'>+55% </span>than lask week</p> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     <div class='col-xl-3 col-sm-6 mb-xl-0 mb-4'> ";
echo "         <div class='card'> ";
echo "         <div class='card-header p-3 pt-2'> ";
echo "             <div class='icon icon-lg icon-shape bg-gradient-primary shadow-primary text-center border-radius-xl mt-n4 position-absolute'> ";
echo "             <i class='bi bi-person-fill h2'></i> ";
echo "             </div> ";
echo "             <div class='text-end pt-1'> ";
echo "             <p class='text-sm mb-0 text-capitalize'>Today's Users</p> ";
echo "             <h4 class='mb-0'>2,300</h4> ";
echo "             </div> ";
echo "         </div> ";
echo "         <hr class='dark horizontal my-0'> ";
echo "         <div class='card-footer p-3'> ";
echo "             <p class='mb-0'><span class='text-success text-sm font-weight-bolder'>+3% </span>than lask month</p> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     <div class='col-xl-3 col-sm-6 mb-xl-0 mb-4'> ";
echo "         <div class='card'> ";
echo "         <div class='card-header p-3 pt-2'> ";
echo "             <div class='icon icon-lg icon-shape bg-gradient-success shadow-success text-center border-radius-xl mt-n4 position-absolute'> ";
echo "             <i class='bi bi-person-fill h2'></i> ";
echo "             </div> ";
echo "             <div class='text-end pt-1'> ";
echo "             <p class='text-sm mb-0 text-capitalize'>New Clients</p> ";
echo "             <h4 class='mb-0'>3,462</h4> ";
echo "             </div> ";
echo "         </div> ";
echo "         <hr class='dark horizontal my-0'> ";
echo "         <div class='card-footer p-3'> ";
echo "             <p class='mb-0'><span class='text-danger text-sm font-weight-bolder'>-2%</span> than yesterday</p> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     <div class='col-xl-3 col-sm-6'> ";
echo "         <div class='card'> ";
echo "         <div class='card-header p-3 pt-2'> ";
echo "             <div class='icon icon-lg icon-shape bg-gradient-info shadow-info text-center border-radius-xl mt-n4 position-absolute'> ";
echo "             <i class='bi bi-cash-coin h2'></i> ";
echo "             </div> ";
echo "             <div class='text-end pt-1'> ";
echo "             <p class='text-sm mb-0 text-capitalize'>Sales</p> ";
echo "             <h4 class='mb-0'>$103,430</h4> ";
echo "             </div> ";
echo "         </div> ";
echo "         <hr class='dark horizontal my-0'> ";
echo "         <div class='card-footer p-3'> ";
echo "             <p class='mb-0'><span class='text-success text-sm font-weight-bolder'>+5% </span>than yesterday</p> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     </div> ";
echo "     <div class='row mt-4'> ";
echo "     <div class='col-lg-4 col-md-6 mt-4 mb-4'> ";
echo "         <div class='card z-index-2 '> ";
echo "         <div class='card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent'> ";
echo "             <div class='bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1'> ";
echo "             <div class='chart'> ";
echo "                 <canvas id='chart-bars' class='chart-canvas' height='170'></canvas> ";
echo "             </div> ";
echo "             </div> ";
echo "         </div> ";
echo "         <div class='card-body'> ";
echo "             <h6 class='mb-0 '>Website Views</h6> ";
echo "             <p class='text-sm '>Last Campaign Performance</p> ";
echo "             <hr class='dark horizontal'> ";
echo "             <div class='d-flex '> ";
echo "             <i class='material-icons text-sm my-auto me-1'>schedule</i> ";
echo "             <p class='mb-0 text-sm'> campaign sent 2 days ago </p> ";
echo "             </div> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     <div class='col-lg-4 col-md-6 mt-4 mb-4'> ";
echo "         <div class='card z-index-2  '> ";
echo "         <div class='card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent'> ";
echo "             <div class='bg-gradient-success shadow-success border-radius-lg py-3 pe-1'> ";
echo "             <div class='chart'> ";
echo "                 <canvas id='chart-line' class='chart-canvas' height='170'></canvas> ";
echo "             </div> ";
echo "             </div> ";
echo "         </div> ";
echo "         <div class='card-body'> ";
echo "             <h6 class='mb-0 '> Daily Sales </h6> ";
echo "             <p class='text-sm '> (<span class='font-weight-bolder'>+15%</span>) increase in today sales. </p> ";
echo "             <hr class='dark horizontal'> ";
echo "             <div class='d-flex '> ";
echo "             <i class='material-icons text-sm my-auto me-1'>schedule</i> ";
echo "             <p class='mb-0 text-sm'> updated 4 min ago </p> ";
echo "             </div> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     <div class='col-lg-4 mt-4 mb-3'> ";
echo "         <div class='card z-index-2 '> ";
echo "         <div class='card-header p-0 position-relative mt-n4 mx-3 z-index-2 bg-transparent'> ";
echo "             <div class='bg-gradient-dark shadow-dark border-radius-lg py-3 pe-1'> ";
echo "             <div class='chart'> ";
echo "                 <canvas id='chart-line-tasks' class='chart-canvas' height='170'></canvas> ";
echo "             </div> ";
echo "             </div> ";
echo "         </div> ";
echo "         <div class='card-body'> ";
echo "             <h6 class='mb-0 '>Completed Tasks</h6> ";
echo "             <p class='text-sm '>Last Campaign Performance</p> ";
echo "             <hr class='dark horizontal'> ";
echo "             <div class='d-flex '> ";
echo "             <i class='material-icons text-sm my-auto me-1'>schedule</i> ";
echo "             <p class='mb-0 text-sm'>just updated</p> ";
echo "             </div> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     </div> ";
echo "     <div class='row mb-4'> ";
echo "     <div class='col-lg-8 col-md-6 mb-md-0 mb-4'> ";
echo "         <div class='card'> ";
echo "         <div class='card-header pb-0'> ";
echo "             <div class='row'> ";
echo "             <div class='col-lg-6 col-7'> ";
echo "                 <h6>Projects</h6> ";
echo "                 <p class='text-sm mb-0'> ";
echo "                 <i class='fa fa-check text-info' aria-hidden='true'></i> ";
echo "                 <span class='font-weight-bold ms-1'>30 done</span> this month ";
echo "                 </p> ";
echo "             </div> ";
echo "             <div class='col-lg-6 col-5 my-auto text-end'> ";
echo "                 <div class='dropdown float-lg-end pe-4'> ";
echo "                 <a class='cursor-pointer' id='dropdownTable' data-bs-toggle='dropdown' aria-expanded='false'> ";
echo "                     <i class='fa fa-ellipsis-v text-secondary'></i> ";
echo "                 </a> ";
echo "                 <ul class='dropdown-menu px-2 py-3 ms-sm-n4 ms-n5' aria-labelledby='dropdownTable'> ";
echo "                     <li><a class='dropdown-item border-radius-md' href='javascript:;'>Action</a></li> ";
echo "                     <li><a class='dropdown-item border-radius-md' href='javascript:;'>Another action</a></li> ";
echo "                     <li><a class='dropdown-item border-radius-md' href='javascript:;'>Something else here</a></li> ";
echo "                 </ul> ";
echo "                 </div> ";
echo "             </div> ";
echo "             </div> ";
echo "         </div> ";
echo "         <div class='card-body px-0 pb-2'> ";
echo "             <div class='table-responsive'> ";
echo "             <table class='table align-items-center mb-0'> ";
echo "                 <thead> ";
echo "                 <tr> ";
echo "                     <th class='text-uppercase text-secondary text-xxs font-weight-bolder opacity-7'>Companies</th> ";
echo "                     <th class='text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2'>Members</th> ";
echo "                     <th class='text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7'>Budget</th> ";
echo "                     <th class='text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7'>Completion</th> ";
echo "                 </tr> ";
echo "                 </thead> ";
echo "                 <tbody> ";
echo "                 <tr> ";
echo "                     <td> ";
echo "                     <div class='d-flex px-2 py-1'> ";
echo "                         <div> ";
echo "                         <img src='".Environment::STATIC_URL."img/small-logos/logo-xd.svg' class='avatar avatar-sm me-3' alt='xd'> ";
echo "                         </div> ";
echo "                         <div class='d-flex flex-column justify-content-center'> ";
echo "                         <h6 class='mb-0 text-sm'>Material XD Version</h6> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td> ";
echo "                     <div class='avatar-group mt-2'> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Ryan Tompson'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-1.jpg' alt='team1'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Romina Hadid'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-2.jpg' alt='team2'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Alexander Smith'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-3.jpg' alt='team3'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Jessica Doe'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-4.jpg' alt='team4'> ";
echo "                         </a> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td class='align-middle text-center text-sm'> ";
echo "                     <span class='text-xs font-weight-bold'> $14,000 </span> ";
echo "                     </td> ";
echo "                     <td class='align-middle'> ";
echo "                     <div class='progress-wrapper w-75 mx-auto'> ";
echo "                         <div class='progress-info'> ";
echo "                         <div class='progress-percentage'> ";
echo "                             <span class='text-xs font-weight-bold'>60%</span> ";
echo "                         </div> ";
echo "                         </div> ";
echo "                         <div class='progress'> ";
echo "                         <div class='progress-bar bg-gradient-info w-60' role='progressbar' aria-valuenow='60' aria-valuemin='0' aria-valuemax='100'></div> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                 </tr> ";
echo "                 <tr> ";
echo "                     <td> ";
echo "                     <div class='d-flex px-2 py-1'> ";
echo "                         <div> ";
echo "                         <img src='".Environment::STATIC_URL."img/small-logos/logo-atlassian.svg' class='avatar avatar-sm me-3' alt='atlassian'> ";
echo "                         </div> ";
echo "                         <div class='d-flex flex-column justify-content-center'> ";
echo "                         <h6 class='mb-0 text-sm'>Add Progress Track</h6> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td> ";
echo "                     <div class='avatar-group mt-2'> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Romina Hadid'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-2.jpg' alt='team5'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Jessica Doe'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-4.jpg' alt='team6'> ";
echo "                         </a> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td class='align-middle text-center text-sm'> ";
echo "                     <span class='text-xs font-weight-bold'> $3,000 </span> ";
echo "                     </td> ";
echo "                     <td class='align-middle'> ";
echo "                     <div class='progress-wrapper w-75 mx-auto'> ";
echo "                         <div class='progress-info'> ";
echo "                         <div class='progress-percentage'> ";
echo "                             <span class='text-xs font-weight-bold'>10%</span> ";
echo "                         </div> ";
echo "                         </div> ";
echo "                         <div class='progress'> ";
echo "                         <div class='progress-bar bg-gradient-info w-10' role='progressbar' aria-valuenow='10' aria-valuemin='0' aria-valuemax='100'></div> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                 </tr> ";
echo "                 <tr> ";
echo "                     <td> ";
echo "                     <div class='d-flex px-2 py-1'> ";
echo "                         <div> ";
echo "                         <img src='".Environment::STATIC_URL."img/small-logos/logo-slack.svg' class='avatar avatar-sm me-3' alt='team7'> ";
echo "                         </div> ";
echo "                         <div class='d-flex flex-column justify-content-center'> ";
echo "                         <h6 class='mb-0 text-sm'>Fix Platform Errors</h6> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td> ";
echo "                     <div class='avatar-group mt-2'> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Romina Hadid'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-3.jpg' alt='team8'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Jessica Doe'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-1.jpg' alt='team9'> ";
echo "                         </a> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td class='align-middle text-center text-sm'> ";
echo "                     <span class='text-xs font-weight-bold'> Not set </span> ";
echo "                     </td> ";
echo "                     <td class='align-middle'> ";
echo "                     <div class='progress-wrapper w-75 mx-auto'> ";
echo "                         <div class='progress-info'> ";
echo "                         <div class='progress-percentage'> ";
echo "                             <span class='text-xs font-weight-bold'>100%</span> ";
echo "                         </div> ";
echo "                         </div> ";
echo "                         <div class='progress'> ";
echo "                         <div class='progress-bar bg-gradient-success w-100' role='progressbar' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'></div> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                 </tr> ";
echo "                 <tr> ";
echo "                     <td> ";
echo "                     <div class='d-flex px-2 py-1'> ";
echo "                         <div> ";
echo "                         <img src='".Environment::STATIC_URL."img/small-logos/logo-spotify.svg' class='avatar avatar-sm me-3' alt='spotify'> ";
echo "                         </div> ";
echo "                         <div class='d-flex flex-column justify-content-center'> ";
echo "                         <h6 class='mb-0 text-sm'>Launch our Mobile App</h6> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td> ";
echo "                     <div class='avatar-group mt-2'> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Ryan Tompson'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-4.jpg' alt='user1'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Romina Hadid'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-3.jpg' alt='user2'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Alexander Smith'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-4.jpg' alt='user3'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Jessica Doe'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-1.jpg' alt='user4'> ";
echo "                         </a> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td class='align-middle text-center text-sm'> ";
echo "                     <span class='text-xs font-weight-bold'> $20,500 </span> ";
echo "                     </td> ";
echo "                     <td class='align-middle'> ";
echo "                     <div class='progress-wrapper w-75 mx-auto'> ";
echo "                         <div class='progress-info'> ";
echo "                         <div class='progress-percentage'> ";
echo "                             <span class='text-xs font-weight-bold'>100%</span> ";
echo "                         </div> ";
echo "                         </div> ";
echo "                         <div class='progress'> ";
echo "                         <div class='progress-bar bg-gradient-success w-100' role='progressbar' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'></div> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                 </tr> ";
echo "                 <tr> ";
echo "                     <td> ";
echo "                     <div class='d-flex px-2 py-1'> ";
echo "                         <div> ";
echo "                         <img src='".Environment::STATIC_URL."img/small-logos/logo-jira.svg' class='avatar avatar-sm me-3' alt='jira'> ";
echo "                         </div> ";
echo "                         <div class='d-flex flex-column justify-content-center'> ";
echo "                         <h6 class='mb-0 text-sm'>Add the New Pricing Page</h6> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td> ";
echo "                     <div class='avatar-group mt-2'> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Ryan Tompson'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-4.jpg' alt='user5'> ";
echo "                         </a> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td class='align-middle text-center text-sm'> ";
echo "                     <span class='text-xs font-weight-bold'> $500 </span> ";
echo "                     </td> ";
echo "                     <td class='align-middle'> ";
echo "                     <div class='progress-wrapper w-75 mx-auto'> ";
echo "                         <div class='progress-info'> ";
echo "                         <div class='progress-percentage'> ";
echo "                             <span class='text-xs font-weight-bold'>25%</span> ";
echo "                         </div> ";
echo "                         </div> ";
echo "                         <div class='progress'> ";
echo "                         <div class='progress-bar bg-gradient-info w-25' role='progressbar' aria-valuenow='25' aria-valuemin='0' aria-valuemax='25'></div> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                 </tr> ";
echo "                 <tr> ";
echo "                     <td> ";
echo "                     <div class='d-flex px-2 py-1'> ";
echo "                         <div> ";
echo "                         <img src='".Environment::STATIC_URL."img/small-logos/logo-invision.svg' class='avatar avatar-sm me-3' alt='invision'> ";
echo "                         </div> ";
echo "                         <div class='d-flex flex-column justify-content-center'> ";
echo "                         <h6 class='mb-0 text-sm'>Redesign New Online Shop</h6> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td> ";
echo "                     <div class='avatar-group mt-2'> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Ryan Tompson'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-1.jpg' alt='user6'> ";
echo "                         </a> ";
echo "                         <a href='javascript:;' class='avatar avatar-xs rounded-circle' data-bs-toggle='tooltip' data-bs-placement='bottom' title='Jessica Doe'> ";
echo "                         <img src='".Environment::STATIC_URL."img/team-4.jpg' alt='user7'> ";
echo "                         </a> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                     <td class='align-middle text-center text-sm'> ";
echo "                     <span class='text-xs font-weight-bold'> $2,000 </span> ";
echo "                     </td> ";
echo "                     <td class='align-middle'> ";
echo "                     <div class='progress-wrapper w-75 mx-auto'> ";
echo "                         <div class='progress-info'> ";
echo "                         <div class='progress-percentage'> ";
echo "                             <span class='text-xs font-weight-bold'>40%</span> ";
echo "                         </div> ";
echo "                         </div> ";
echo "                         <div class='progress'> ";
echo "                         <div class='progress-bar bg-gradient-info w-40' role='progressbar' aria-valuenow='40' aria-valuemin='0' aria-valuemax='40'></div> ";
echo "                         </div> ";
echo "                     </div> ";
echo "                     </td> ";
echo "                 </tr> ";
echo "                 </tbody> ";
echo "             </table> ";
echo "             </div> ";
echo "         </div> ";
echo "         </div> ";
echo "     </div> ";
echo "     <div class='col-lg-4 col-md-6'> ";
echo "         <div class='card h-100'> ";
echo "         <div class='card-header pb-0'> ";
echo "             <h6>Orders overview</h6> ";
echo "             <p class='text-sm'> ";
echo "             <i class='fa fa-arrow-up text-success' aria-hidden='true'></i> ";
echo "             <span class='font-weight-bold'>24%</span> this month ";
echo "             </p> ";
echo "         </div> ";
echo "         <div class='card-body p-3'> ";
echo "             <div class='timeline timeline-one-side'> ";
echo "             <div class='timeline-block mb-3'> ";
echo "                 <span class='timeline-step'> ";
echo "                 <i class='bi bi-bell-fill text-success fs-5'></i> ";
echo "                 </span> ";
echo "                 <div class='timeline-content'> ";
echo "                 <h6 class='text-dark text-sm font-weight-bold mb-0'>$2400, Design changes</h6> ";
echo "                 <p class='text-secondary font-weight-bold text-xs mt-1 mb-0'>22 DEC 7:20 PM</p> ";
echo "                 </div> ";
echo "             </div> ";
echo "             <div class='timeline-block mb-3'> ";
echo "                 <span class='timeline-step'> ";
echo "                 <i class='bi bi-code text-danger fs-5'></i> ";
echo "                 </span> ";
echo "                 <div class='timeline-content'> ";
echo "                 <h6 class='text-dark text-sm font-weight-bold mb-0'>New order #1832412</h6> ";
echo "                 <p class='text-secondary font-weight-bold text-xs mt-1 mb-0'>21 DEC 11 PM</p> ";
echo "                 </div> ";
echo "             </div> ";
echo "             <div class='timeline-block mb-3'> ";
echo "                 <span class='timeline-step'> ";
echo "                 <i class='bi bi-cart4 text-info fs-5'></i> ";
echo "                 </span> ";
echo "                 <div class='timeline-content'> ";
echo "                 <h6 class='text-dark text-sm font-weight-bold mb-0'>Server payments for April</h6> ";
echo "                 <p class='text-secondary font-weight-bold text-xs mt-1 mb-0'>21 DEC 9:34 PM</p> ";
echo "                 </div> ";
echo "             </div> ";
echo "             <div class='timeline-block mb-3'> ";
echo "                 <span class='timeline-step'> ";
echo "                 <i class='bi bi-credit-card text-warning fs-5'></i> ";
echo "                 </span> ";
echo "                 <div class='timeline-content'> ";
echo "                 <h6 class='text-dark text-sm font-weight-bold mb-0'>New card added for order #4395133</h6> ";
echo "                 <p class='text-secondary font-weight-bold text-xs mt-1 mb-0'>20 DEC 2:20 AM</p> ";
echo "                 </div> ";
echo "             </div> ";
echo "             <div class='timeline-block mb-3'> ";
echo "                 <span class='timeline-step'> ";
echo "                 <i class='bi bi-key-fill text-primary fs-5'></i> ";
echo "                 </span> ";
echo "                 <div class='timeline-content'> ";
echo "                 <h6 class='text-dark text-sm font-weight-bold mb-0'>Unlock packages for development</h6> ";
echo "                 <p class='text-secondary font-weight-bold text-xs mt-1 mb-0'>18 DEC 4:54 AM</p> ";
echo "                 </div> ";
echo "             </div> ";
echo "             <div class='timeline-block'> ";
echo "                 <span class='timeline-step'> ";
echo "                 <i class='bi bi-cash-stack text-dark fs-5'></i> ";
echo "                 </span> ";
echo "                 <div class='timeline-content'> ";
echo "                 <h6 class='text-dark text-sm font-weight-bold mb-0'>New order #9583120</h6> ";
echo "                 <p class='text-secondary font-weight-bold text-xs mt-1 mb-0'>17 DEC</p> ";
echo "                 </div> ";
echo "             </div> ";
echo "             </div> ";
echo "         </div> ";
echo "     </div> ";
echo " </div> ";

echo " <script>  ";
echo "   var ctx = document.getElementById('chart-bars').getContext('2d'); ";

echo "   new Chart(ctx, { ";
echo "     type: 'bar', ";
echo "     data: { ";
echo "       labels: ['M', 'T', 'W', 'T', 'F', 'S', 'S'], ";
echo "       datasets: [{ ";
echo "         label: 'Sales', ";
echo "         tension: 0.4, ";
echo "         borderWidth: 0, ";
echo "         borderRadius: 4, ";
echo "         borderSkipped: false, ";
echo "         backgroundColor: 'rgba(255, 255, 255, .8)', ";
echo "         data: [50, 20, 10, 22, 50, 10, 40], ";
echo "         maxBarThickness: 6 ";
echo "       }, ], ";
echo "     }, ";
echo "     options: { ";
echo "       responsive: true, ";
echo "       maintainAspectRatio: false, ";
echo "       plugins: { ";
echo "         legend: { ";
echo "           display: false, ";
echo "         } ";
echo "       }, ";
echo "       interaction: { ";
echo "         intersect: false, ";
echo "         mode: 'index', ";
echo "       }, ";
echo "       scales: { ";
echo "         y: { ";
echo "           grid: { ";
echo "             drawBorder: false, ";
echo "             display: true, ";
echo "             drawOnChartArea: true, ";
echo "             drawTicks: false, ";
echo "             borderDash: [5, 5], ";
echo "             color: 'rgba(255, 255, 255, .2)' ";
echo "           }, ";
echo "           ticks: { ";
echo "             suggestedMin: 0, ";
echo "             suggestedMax: 500, ";
echo "             beginAtZero: true, ";
echo "             padding: 10, ";
echo "             font: { ";
echo "               size: 14, ";
echo "               weight: 300, ";
echo "               family: 'Roboto', ";
echo "               style: 'normal', ";
echo "               lineHeight: 2 ";
echo "             }, ";
echo "             color: '#fff' ";
echo "           }, ";
echo "         }, ";
echo "         x: { ";
echo "           grid: { ";
echo "             drawBorder: false, ";
echo "             display: true, ";
echo "             drawOnChartArea: true, ";
echo "             drawTicks: false, ";
echo "             borderDash: [5, 5], ";
echo "             color: 'rgba(255, 255, 255, .2)' ";
echo "           }, ";
echo "           ticks: { ";
echo "             display: true, ";
echo "             color: '#f8f9fa', ";
echo "             padding: 10, ";
echo "             font: { ";
echo "               size: 14, ";
echo "               weight: 300, ";
echo "               family: 'Roboto', ";
echo "               style: 'normal', ";
echo "               lineHeight: 2 ";
echo "             }, ";
echo "           } ";
echo "         }, ";
echo "       }, ";
echo "     }, ";
echo "   }); ";

echo "   var ctx2 = document.getElementById('chart-line').getContext('2d'); ";

echo "   new Chart(ctx2, { ";
echo "     type: 'line', ";
echo "     data: { ";
echo "       labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], ";
echo "       datasets: [{ ";
echo "         label: 'Mobile apps', ";
echo "         tension: 0, ";
echo "         borderWidth: 0, ";
echo "         pointRadius: 5, ";
echo "         pointBackgroundColor: 'rgba(255, 255, 255, .8)', ";
echo "         pointBorderColor: 'transparent', ";
echo "         borderColor: 'rgba(255, 255, 255, .8)', ";
echo "         borderColor: 'rgba(255, 255, 255, .8)', ";
echo "         borderWidth: 4, ";
echo "         backgroundColor: 'transparent', ";
echo "         fill: true, ";
echo "         data: [50, 40, 300, 320, 500, 350, 200, 230, 500], ";
echo "         maxBarThickness: 6 ";

echo "       }], ";
echo "     }, ";
echo "     options: { ";
echo "       responsive: true, ";
echo "       maintainAspectRatio: false, ";
echo "       plugins: { ";
echo "         legend: { ";
echo "           display: false, ";
echo "         } ";
echo "       }, ";
echo "       interaction: { ";
echo "         intersect: false, ";
echo "         mode: 'index', ";
echo "       }, ";
echo "       scales: { ";
echo "         y: { ";
echo "           grid: { ";
echo "             drawBorder: false, ";
echo "             display: true, ";
echo "             drawOnChartArea: true, ";
echo "             drawTicks: false, ";
echo "             borderDash: [5, 5], ";
echo "             color: 'rgba(255, 255, 255, .2)' ";
echo "           }, ";
echo "           ticks: { ";
echo "             display: true, ";
echo "             color: '#f8f9fa', ";
echo "             padding: 10, ";
echo "             font: { ";
echo "               size: 14, ";
echo "               weight: 300, ";
echo "               family: 'Roboto', ";
echo "               style: 'normal', ";
echo "               lineHeight: 2 ";
echo "             }, ";
echo "           } ";
echo "         }, ";
echo "         x: { ";
echo "           grid: { ";
echo "             drawBorder: false, ";
echo "             display: false, ";
echo "             drawOnChartArea: false, ";
echo "             drawTicks: false, ";
echo "             borderDash: [5, 5] ";
echo "           }, ";
echo "           ticks: { ";
echo "             display: true, ";
echo "             color: '#f8f9fa', ";
echo "             padding: 10, ";
echo "             font: { ";
echo "               size: 14, ";
echo "               weight: 300, ";
echo "               family: 'Roboto', ";
echo "               style: 'normal', ";
echo "               lineHeight: 2 ";
echo "             }, ";
echo "           } ";
echo "         }, ";
echo "       }, ";
echo "     }, ";
echo "   }); ";

echo "   var ctx3 = document.getElementById('chart-line-tasks').getContext('2d'); ";

echo "   new Chart(ctx3, { ";
echo "     type: 'line', ";
echo "     data: { ";
echo "       labels: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], ";
echo "       datasets: [{ ";
echo "         label: 'Mobile apps', ";
echo "         tension: 0, ";
echo "         borderWidth: 0, ";
echo "         pointRadius: 5, ";
echo "         pointBackgroundColor: 'rgba(255, 255, 255, .8)', ";
echo "         pointBorderColor: 'transparent', ";
echo "         borderColor: 'rgba(255, 255, 255, .8)', ";
echo "         borderWidth: 4, ";
echo "         backgroundColor: 'transparent', ";
echo "         fill: true, ";
echo "         data: [50, 40, 300, 220, 500, 250, 400, 230, 500], ";
echo "         maxBarThickness: 6 ";

echo "       }], ";
echo "     }, ";
echo "     options: { ";
echo "       responsive: true, ";
echo "       maintainAspectRatio: false, ";
echo "       plugins: { ";
echo "         legend: { ";
echo "           display: false, ";
echo "         } ";
echo "       }, ";
echo "       interaction: { ";
echo "         intersect: false, ";
echo "         mode: 'index', ";
echo "       }, ";
echo "       scales: { ";
echo "         y: { ";
echo "           grid: { ";
echo "             drawBorder: false, ";
echo "             display: true, ";
echo "             drawOnChartArea: true, ";
echo "             drawTicks: false, ";
echo "             borderDash: [5, 5], ";
echo "             color: 'rgba(255, 255, 255, .2)' ";
echo "           }, ";
echo "           ticks: { ";
echo "             display: true, ";
echo "             padding: 10, ";
echo "             color: '#f8f9fa', ";
echo "             font: { ";
echo "               size: 14, ";
echo "               weight: 300, ";
echo "               family: 'Roboto', ";
echo "               style: 'normal', ";
echo "               lineHeight: 2 ";
echo "             }, ";
echo "           } ";
echo "         }, ";
echo "         x: { ";
echo "           grid: { ";
echo "             drawBorder: false, ";
echo "             display: false, ";
echo "             drawOnChartArea: false, ";
echo "             drawTicks: false, ";
echo "             borderDash: [5, 5] ";
echo "           }, ";
echo "           ticks: { ";
echo "             display: true, ";
echo "             color: '#f8f9fa', ";
echo "             padding: 10, ";
echo "             font: { ";
echo "               size: 14, ";
echo "               weight: 300, ";
echo "               family: 'Roboto', ";
echo "               style: 'normal', ";
echo "               lineHeight: 2 ";
echo "             }, ";
echo "           } ";
echo "         }, ";
echo "       }, ";
echo "     }, ";
echo "   }); ";
echo " </script> ";

?>